### ISSUE TITLE
[question] Does it work with subdomain?

### ISSUE THREAD

**Issue by finzzz** [giuseppelt/EmailFlare#13]
I notice that setting this up using subdomain doesn't work (I'm aware we can use replyto field). Here is my setup:
- Domain lockdown TXT: `_mailchannels.subdomain` => `v=mc1 cfid=finzzz.workers.dev cfid=subdmain.xxx.yyy`
- MX: `subdomain` => 10 `somewhere`
- SPF TXT: `subdomain` => `v=spf1 include:_spf.mx.cloudflare.net include:relay.mailchannels.net -all`
- DKIM TXT `mailchannels._domainkey.subdomain` => `v=DKIM1; k=rsa; p=verylongstuffs`

I keep getting this error
```
{"errors":["Failed to send email: 550 5.7.1 This sender is not authorized to send from subdomain.xxx.yyy. See https://bit.ly/domain-lockdown. cfid=xxx.yyy"]}
```

Does anyone able to get this work on subdomain?

**Comment by giuseppelt** [comment]
Mailchannels doesn't support subdomains, only top level.
