### ISSUE TITLE
HTTP 400 Error Auto-deploy

### ISSUE THREAD

**Issue by Oosmus** [giuseppelt/EmailFlare#2]
Following the guide [https://www.breakp.dev/blog/email-flare-send-from-worker-for-free/](url), I have ran into an issue upon clicking Deploy. 

[HTTP-400] Cloudflare deploy error: HTTP-400 is all I'm shown from the tool. 
![image](https://github.com/giuseppelt/EmailFlare/assets/33063933/59359ba6-1cf1-41e3-81c9-a9f0c12738ec)
Here's a clip of what I've filled out in case I've done something wrong here.

**Comment by giuseppelt** [comment]
Http-400, means some data you put is wrong.

From the clip, maybe it's the worker name. You should not put the address, just the name, the one that appears on the dashboard.

**Comment by Oosmus** [comment]
You are entirely correct, that was the issue. I misread the instructions and thought it meant the full address, not the name. 

Side-question - would there be a possibility of being able to have it redirect emails to different mailboxes. Basically handle in-bound alongside outbound?

**Comment by giuseppelt** [comment]
With EmailFlare is not possibile, as it's send-only.

I'm building something that does that: https://combustion.email
Join the waitlist you interested, I'll contact you when it's ready to try it for free.

**Comment by louis-eyond** [comment]
> Side-question - would there be a possibility of being able to have it redirect emails to different mailboxes. Basically handle in-bound alongside outbound?

Cloudflare added exactly that (was it last year?).  Take a look at "Email Routing" in the domain settings of Cloudflare Dashboard...   You can set it up to forward incoming emails to your CF domain to any email address, basically handling incoming at your domain.

Then use EmailFlare for the outgoing from the same domain, and you have full email on your own domain.

> I'm building something that does that: https://combustion.email/
I did sign-up to get notified on that too, sounds interesting!
