### ISSUE TITLE
Uncaught Error: No such module "node:async_hooks". 

### ISSUE THREAD

**Issue by Nick-Gatti** [giuseppelt/EmailFlare#3]
Error when manually deploying in CloudFlare:

Uncaught Error: No such module "node:async_hooks".
  imported from "worker.js"

**Comment by giuseppelt** [comment]
Did you find the section in the dashboard? I don't think you can set the flags at the moment via dashboard.

Maybe a fallback to a command line is required.

**Comment by giuseppelt** [comment]
No prob, I will update the guide to include the command. I let you know.
________________________________

**Comment by giuseppelt** [comment]
Updated blog post with instruction to deploy via command line.
