### ISSUE TITLE
Feature Request - Allow users to send emails in html format

### ISSUE THREAD

**Issue by Jazzahn** [giuseppelt/EmailFlare#7]
In order to ensure proper styling we use HTML and CSS to code our emails before sending. It would be super helpful to be able to just copy and paste html and send through this app. Thanks!

**Comment by giuseppelt** [comment]
Hi @Jazzahn ,sorry for late answer.
I was very busy, working on an evolution of EmailFlare.

It's https://combustion.email
Where you can send emails and manage multi domains very easily.
I already implemented the Raw HTML feature there.
If you want to give it a try let me know.

I will implement this anyway this weekend.
