### ISSUE TITLE
DKIM public key and private key mismatch: fail to get public key from DNS record

### ISSUE THREAD

**Issue by PIKACHUIM** [giuseppelt/EmailFlare#8]
[HTTP-500] {"errors":["bad request - DKIM public key and private key mismatch: fail to get public key from DNS record"]}
However, I have already set up DKIM key:
![Q20231228124118](https://github.com/giuseppelt/EmailFlare/assets/40362270/f62080c4-1ddc-4b7e-9355-1d55ac9a4421)

**Comment by PIKACHUIM** [comment]
Please help me to solve this problem, thanks!
If any log is need, feel free to reply me to supply

**Comment by PIKACHUIM** [comment]
Closed for cloudflare have cache and not take effort now.

**Comment by ccn110116** [comment]
How to fix it?

**Comment by PIKACHUIM** [comment]
1.Delete DKIM record in cloudflare
2.Wait for about 3h~3days
3.Add DKIM record again
4.Redeploy EmailFlare
